server:
  port: 8001
  
mybatis:  type-aliases-package: com.microservicecloud.api  mapper-locations:  - classpath:mapper/*.xml
  
spring:  datasource:    url: jdbc:mysql://localhost:3306/test?useSSL=true    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: a111
    dbcp2:      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200        
